project:
  type: website
  output-dir: docs

  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "Edifofon Akpan"
  description: "Edifofon is a research associate at The University of Melbourne Australia and Helpman Institute Abuja Nigeria"
  favicon: "/files/icon.png"
  site-url: "https://www.edifofon.com"
  repo-url: "https://github.com/EdifofonA/website"
  
  navbar:
    pinned: true

    left:
      - text: "About"
        href: "index.qmd"
      - text: "CV"
        href: "cv/index.qmd"
      - text: "Blog"
        href: "blog/index.qmd"
        
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:hello@edifofon.com"
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/EdifofonA
      - icon: github
        aria-label: github
        href: https://github.com/EdifofonA
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/edifofon

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 850px
      margin-width: 250px
      gutter-width: 1.5rem
editor: visual

