---
title: "Costs of primary healthcare presentations and hospital admissions for scabies and related skin infections in Fiji, 2018-2019"
date: 2024-05-27
author:
  - name: Edifofon Akpan
    orcid: 0000-0003-3506-7590
    affiliation: Melbourne School of Population and Global Health
  - name: Natalie Carvalho
    orcid: 0000-0002-5599-2209
    affiliation: Melbourne School of Population and Global Health
categories:
  - Costing
  - R
  - Global health
pub-info:
  reference: >-
    <strong>Akpan E</strong>, Thean LJ, Baskota R, Mani J, Mow M, Sahukhan A, Kama M, Tuicakau M, Kado J, Romani L, Engelman D, Whitfeld M, Kaldor J, Steer A, and Carvalho N. “Costs of primary healthcare presentations and hospital admissions for scabies and related skin infections in Fiji, 2018-2019.” <em>Journal</em> 2022; ##(#):##–##. doi:<a href="https://doi.org/10.########"><code>10.########</code></a>
  links:
  - name: Code notebook
    url: https://github.com/EdifofonA/bigshift-scabiesSSTI-costs
    icon: fa-brands fa-github
  # - name: Final version
  #   url: https://doi.org/10.1093/ajcn/nqac225
  #   icon: fa-solid fa-scroll
  # - name: Code notebook
  #   url: https://github.com/EdifofonA/brisc-cost-effectiveness
  #   icon: fa-brands fa-github
  # - name: Add to Zotero
  #   url: https://www.zotero.org/save?type=doi&q=10.1093/ajcn/nqac225
  #   icon: ai ai-zotero

doi: pending
---

## Abstract

**Background:** Scabies and related bacterial skin and soft tissue infections (SSTIs) are highly prevalent in many tropical, low- and middle-income settings. These skin conditions contribute to higher healthcare costs and burdens on healthcare systems. The Big Skin Health Intervention Fiji Trial (“Big SHIFT”) carried out surveillance for scabies and related SSTIs from July 2018 to June 2019 in the Northern Division of Fiji, an area with high prevalence of scabies, prior to a division-wide ivermectin-based mass drug administration campaign. .

**Methods:** Using data from Big SHIFT, we sought to estimate the annual direct healthcare costs of scabies and related SSTIs for the Northern Division and extrapolate these costs to the national level. We also assessed non-scabies-related SSTIs. We categorized SSTIs as being potentially scabies-related or not scabies related, based on a previous study. The analysis used a health system perspective, with the main resource use categories of primary healthcare (PHC) visits, bed days, medications, and diagnostics. We extrapolated the total annual number of cases and direct healthcare costs for all divisions in Fiji based upon previous scabies and impetigo prevalence data across all divisions.

**Results:** The average cost per PHC presentation for scabies was US\$17.7, and for scabies-related SSTI was \$18.3. The average cost per hospital admission for scabies-related SSTI case was \$439. The estimated annual healthcare costs of scabies and related SSTIs in Fiji was US\$3.0 million, with cost per capita of \$3.3.

**Conclusions:** Scabies and related SSTIs lead to a heavy economic burden in Fiji and prevention would reduce these healthcare costs.

## Figures

![Figure 1. One-way sensitivity analysis on the impact of changing the base case parameter values to low and high values on the total annual healthcare costs (in 2020 US\$) of scabies and related SSTIs in Fiji. Total annual cost is indicated by the black reference line (\$2.95 million). See Table 1 for the ranges used for this sensitivity analysis. ICU, intensive care unit; PHC, primary healthcare; SSTI, skin and soft tissue infection.](tornado-total-costs.png)
